[build]
rustdocflags = [
    "--cfg",
    "docsrs",
    "-Zunstable-options",
    "--generate-link-to-definition",
    "--html-in-header",
    "viewer/doc/katex-header.html",
    "--html-in-header",
    "viewer/doc/docs.html",
]

[target.wasm32-unknown-unknown]
rustflags = [
    "-Ctarget-cpu=mvp",
    "-Ctarget-feature=+multivalue,+mutable-globals,+reference-types,+sign-ext",
    "--cfg",
    "web_sys_unstable_apis",
    "--cfg",
    'getrandom_backend="wasm_js"',
]

[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["optimize_for_size"]          #,"panic_immediate_abort"]
