[build]
rustdocflags = [
    "--cfg",
    "docsrs",
    "-Zunstable-options",
    "--generate-link-to-definition",
    "--html-in-header",
    "parser/doc/katex-header.html",
    "--html-in-header",
    "parser/doc/docs.html",
]
