[tasks.test-no-features]
command = "cargo"
install_crate = false
args = ["+nightly", "test", "--no-default-features"]

[tasks.test-rdf]
command = "cargo"
install_crate = false
args = ["+nightly", "test", "--features=rdf"]

[tasks.test-typescript]
command = "cargo"
install_crate = false
args = ["+nightly", "test", "--features=typescript"]

[tasks.test-all-features]
command = "cargo"
install_crate = false
args = ["+nightly", "test", "--all-features"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.all-tests]
dependencies = [
    "test-no-features",
    "test-rdf",
    "test-typescript",
    "test-all-features",
    "clean"
]

[tasks.doc]
command = "cargo"
install_crate = false
args = ["+nightly", "doc", "--no-deps", "--all-features"]
