[env]
LEPTOS_SASS_VERSION = "1.89.2"

[tasks.test-no-features]
command = "cargo"
install_crate = false
args = ["+nightly", "test", "--no-default-features"]

[tasks.test-all-features]
command = "cargo"
install_crate = false
args = ["+nightly", "test", "--all-features"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.all-tests]
dependencies = ["test-no-features", "test-all-features","clean"]

[tasks.doc]
command = "cargo"
install_crate = false
args = ["+nightly", "doc", "--no-deps", "--all-features"]


[tasks.wasm-pack]
#env = { "RUSTFLAGS" = "--cfg getrandom_backend=\"wasm_js\" -Ctarget-cpu=mvp -Ctarget-feature=+multivalue,+mutable-globals,+reference-types,+sign-ext" }
install_crate = "wasm-pack"
toolchain = "nightly"
command = "wasm-pack"
args = [
    "build",
    #"--verbose",
    "--target",
    "no-modules",
    "--out-name",
    "ftml",
    "--out-dir",
    "../bin/viewer",
    "--",
    "--target",
    "wasm32-unknown-unknown",
    "-Z",
    "build-std=std,panic_abort,core,alloc",
    "-Z",
    "build-std-features=optimize_for_size", #,panic_immediate_abort",
    "--timings",
]

[tasks.patch-js]
script = '''
sed -i 's/wasm_bindgen = Object/ftmlViewer = Object/g' ../bin/viewer/ftml.js
echo "ftmlViewer();" >> ../bin/viewer/ftml.js
'''

[tasks.patch-dev]
script = '''
#sed -i 's/wasm_bindgen/ftmlViewer/g' ../bin/viewer-dev/ftml.js
echo "wasm_bindgen();" >> ../bin/viewer-dev/ftml.js
'''

[tasks.copy]
script_runner = "@shell"
script = '''
    cp ../bin/viewer/ftml.js ../tests/leptos/public/ftml.js
    cp ../bin/viewer/ftml_bg.wasm ../tests/leptos/public/ftml_bg.wasm
'''

[tasks.copy-dev]
script_runner = "@shell"
script = '''
    cp ../bin/viewer-dev/ftml.js ../tests/leptos/public/ftml.js
    cp ../bin/viewer-dev/ftml_bg.wasm ../tests/leptos/public/ftml_bg.wasm
'''

[tasks.default]
clear = true
dependencies = ["wasm-pack", "patch-js", "copy"]

[tasks.dev]
clear = true
dependencies = ["wasm-pack-dev", "patch-dev","copy-dev"]

[tasks.wasm-pack-dev]
#env = { "RUSTFLAGS" = "--cfg getrandom_backend=\"wasm_js\" -Ctarget-cpu=mvp -Ctarget-feature=+multivalue,+mutable-globals,+reference-types,+sign-ext" }
install_crate = "wasm-pack"
command = "wasm-pack"
args = [
    "build",
    #"--verbose",
    "--target",
    "no-modules",
    "--dev",
    "--out-name",
    "ftml",
    "--out-dir",
    "../bin/viewer-dev",
    "--",
    "--target",
    "wasm32-unknown-unknown",
    #"-Z",
    #"build-std=std,panic_abort,core,alloc",
    #"-Z",
    #"build-std-features=optimize_for_size", #,panic_immediate_abort",
    "--timings",
]

[tasks.split]
clear = true
dependencies = ["wasm-pack-split", "patch-js", "copy"]

# wasm_split_cli ftml_viewer.wasm ./wasm
# wasm-bindgen main.wasm --out-dir ./out --target no-modules --no-demangle --keep-lld-exports
# wasm-opt -Os path -o path
[tasks.build-wasm-relocs]
env = { "RUSTFLAGS" = "-Clink-args=--emit-relocs -Ctarget-cpu=mvp -Ctarget-feature=+multivalue,+mutable-globals,+reference-types,+sign-ext --cfg web_sys_unstable_apis --cfg getrandom_backend=\"wasm_js\"" }
command = "cargo"
toolchain = "nightly"
args = [
    "build",
    #"--verbose",
    "--release",
    "--target",
    "wasm32-unknown-unknown",
    "--features=wasm-split",
    "-Z",
    "build-std=std,panic_abort,core,alloc",
    "-Z",
    "build-std-features=optimize_for_size", #,panic_immediate_abort",
    "--timings",
]
