[env]
LEPTOS_SASS_VERSION = "1.89.2"

[tasks.test-no-features]
command = "cargo"
install_crate = false
args = ["+nightly", "test", "--no-default-features"]

[tasks.test-all-features]
command = "cargo"
install_crate = false
args = ["+nightly", "test", "--all-features"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.all-tests]
dependencies = ["test-no-features", "test-all-features","clean"]

[tasks.doc]
command = "cargo"
install_crate = false
args = ["+nightly", "doc", "--no-deps", "--all-features"]


[tasks.wasm-pack]
#env = { "RUSTFLAGS" = "--cfg getrandom_backend=\"wasm_js\" -Ctarget-cpu=mvp -Ctarget-feature=+multivalue,+mutable-globals,+reference-types,+sign-ext" }
install_crate = "wasm-pack"
toolchain = "nightly"
command = "wasm-pack"
args = [
    "build",
    "--target",
    "no-modules",
    "--out-name",
    "ftml",
    "--out-dir",
    "../bin/viewer",
    "--",
    "--target",
    "wasm32-unknown-unknown",
    "-Z",
    "build-std=std,panic_abort,core,alloc",
    "-Z",
    "build-std-features=optimize_for_size", #,panic_immediate_abort",
    "--timings",
]

[tasks.patch-js]
script = '''
sed -i 's/wasm_bindgen/ftmlViewer/g' ../bin/viewer/ftml.js
echo "ftmlViewer();" >> ../bin/viewer/ftml.js
'''

[tasks.ts]
#env = { "RUSTFLAGS" = "--cfg getrandom_backend=\"wasm_js\" -Ctarget-cpu=mvp -Ctarget-feature=+multivalue,+mutable-globals,+reference-types,+sign-ext" }
install_crate = "wasm-pack"
command = "wasm-pack"
toolchain = "nightly"
args = [
    "build",
    "--out-dir",
    "../bin/ts",
    "--out-name",
    "ftml-viewer-base",
    "--target",
    "web",
    "--",
    "--features",
    "typescript",
    "--target",
    "wasm32-unknown-unknown",
    "-Z",
    "build-std=std,panic_abort,core,alloc",
    "-Z",
    "build-std-features=optimize_for_size", #,panic_immediate_abort",
    "--timings",
]

[tasks.copy]
script_runner = "@shell"
script = '''
    cp ../bin/viewer/ftml.js ../tests/leptos/public/ftml.js
    cp ../bin/viewer/ftml_bg.wasm ../tests/leptos/public/ftml_bg.wasm
'''


[tasks.default]
clear = true
dependencies = ["wasm-pack", "patch-js", "copy"]
