[tasks.all-tests]
command = "cargo"
install_crate = false
args = ["+nightly", "test", "--all-features"]

[tasks.doc]
command = "cargo"
install_crate = false
args = ["+nightly", "doc", "--no-deps", "--all-features"]
