[tasks.test-no-features]
command = "cargo"
install_crate = false
args = ["+nightly", "test", "--no-default-features"]

[tasks.test-interned]
command = "cargo"
install_crate = false
args = ["+nightly", "test", "--features=interned"]

[tasks.test-serde]
command = "cargo"
install_crate = false
args = ["+nightly", "test", "--features=serde"]

[tasks.test-typescript]
command = "cargo"
install_crate = false
args = ["+nightly", "test", "--features=typescript"]

[tasks.test-components]
command = "cargo"
install_crate = false
args = ["+nightly", "test", "--features=components"]

[tasks.test-leptos]
command = "cargo"
install_crate = false
args = ["+nightly", "test", "--features=leptos"]

[tasks.test-tantivy]
command = "cargo"
install_crate = false
args = ["+nightly", "test", "--features=tantivy"]

[tasks.test-all-features]
command = "cargo"
install_crate = false
args = ["+nightly", "test", "--all-features"]

[tasks.all-tests]
dependencies = [
    "test-no-features",
    "test-interned",
    "test-serde",
    "test-typescript",
    "test-components",
    "test-leptos",
    "test-tantivy",
    "test-all-features",
]

[tasks.doc]
command = "cargo"
install_crate = false
args = ["+nightly", "doc", "--no-deps", "--all-features"]
